"""
Game Server Definitions for Proxmox Deployer
Comprehensive catalog of 250+ deployable game servers with configuration templates.
"""

# Server categories for organization
CATEGORIES = {
    'source': {'name': 'Source Engine', 'icon': 'cpu', 'color': '#ff9800'},
    'survival': {'name': 'Survival Games', 'icon': 'shield', 'color': '#4caf50'},
    'classic': {'name': 'Classic Games', 'icon': 'star', 'color': '#9c27b0'},
    'sandbox': {'name': 'Sandbox & Building', 'icon': 'box', 'color': '#2196f3'},
    'mmo': {'name': 'MMO Emulators', 'icon': 'users', 'color': '#e91e63'},
    'management': {'name': 'Server Management', 'icon': 'server', 'color': '#607d8b'},
    'rpg': {'name': 'RPG & Tabletop', 'icon': 'map', 'color': '#795548'},
    'windows': {'name': 'Windows Games', 'icon': 'monitor', 'color': '#00bcd4'},
    'milsim': {'name': 'Military Simulation', 'icon': 'target', 'color': '#4a5568'},
    'racing': {'name': 'Racing & Simulation', 'icon': 'truck', 'color': '#dc2626'},
    'roleplay': {'name': 'Roleplay', 'icon': 'message-circle', 'color': '#7c3aed'},
    'arena': {'name': 'Arena & Competitive', 'icon': 'crosshair', 'color': '#ef4444'},
    'coop': {'name': 'Co-op & Multiplayer', 'icon': 'users', 'color': '#10b981'},
    'voice': {'name': 'Voice & Communication', 'icon': 'mic', 'color': '#6366f1'},
}

# Helper function to create standard game server entry
def _server(name, hostname, description, category, steam_app_id=None, cores=2, memory=4096,
            disk_size=20, ports=None, protocol='UDP/TCP', tags=None, icon='server',
            linuxgsm_name=None, deployment_type='lxc'):
    """Create a standard game server configuration."""
    return {
        'name': name,
        'hostname': hostname,
        'description': description,
        'category': category,
        'deployment_type': deployment_type,
        'steam_app_id': steam_app_id,
        'cores': cores,
        'memory': memory,
        'disk_size': disk_size,
        'ports': ports or [27015],
        'protocol': protocol,
        'tags': tags or [category],
        'icon': icon,
        'linuxgsm_name': linuxgsm_name,
        'docker_image': 'cm2network/steamcmd' if steam_app_id else None,
        'privileged': False,
        'nesting': True,
        'env_vars': [],
    }

# Game server definitions - 250+ games
GAME_SERVERS = {
    # ============================================
    # SOURCE ENGINE GAMES (34 games)
    # ============================================
    'cs16': _server('Counter-Strike 1.6', 'cs16-server', 'Classic Counter-Strike 1.6 dedicated server', 'source',
                    steam_app_id=90, cores=2, memory=2048, disk_size=15, ports=[27015], linuxgsm_name='csserver'),
    'cs2': _server('Counter-Strike 2', 'cs2-server', 'Counter-Strike 2 dedicated server (Source 2)', 'source',
                   steam_app_id=730, cores=4, memory=8192, disk_size=50, ports=[27015, 27020], linuxgsm_name='cs2server'),
    'css': _server('Counter-Strike: Source', 'css-server', 'Counter-Strike: Source dedicated server', 'source',
                   steam_app_id=232330, cores=2, memory=4096, disk_size=25, ports=[27015], linuxgsm_name='cssserver'),
    'cscz': _server('Counter-Strike: Condition Zero', 'cscz-server', 'Counter-Strike: Condition Zero dedicated server', 'source',
                    steam_app_id=80, cores=2, memory=2048, disk_size=15, ports=[27015], linuxgsm_name='csczserver'),
    'csgo': _server('Counter-Strike: Global Offensive', 'csgo-server', 'CS:GO dedicated server (legacy)', 'source',
                    steam_app_id=740, cores=4, memory=8192, disk_size=40, ports=[27015], linuxgsm_name='csgoserver'),
    'tf2': _server('Team Fortress 2', 'tf2-server', 'Team Fortress 2 dedicated server', 'source',
                   steam_app_id=232250, cores=4, memory=4096, disk_size=30, ports=[27015], linuxgsm_name='tf2server'),
    'tfc': _server('Team Fortress Classic', 'tfc-server', 'Team Fortress Classic dedicated server', 'source',
                   steam_app_id=20, cores=2, memory=2048, disk_size=15, ports=[27015], linuxgsm_name='tfcserver'),
    'gmod': _server("Garry's Mod", 'gmod-server', "Garry's Mod dedicated server", 'source',
                    steam_app_id=4020, cores=4, memory=8192, disk_size=40, ports=[27015], linuxgsm_name='gmodserver'),
    'l4d': _server('Left 4 Dead', 'l4d-server', 'Left 4 Dead dedicated server', 'source',
                   steam_app_id=222840, cores=2, memory=4096, disk_size=25, ports=[27015], linuxgsm_name='l4dserver'),
    'l4d2': _server('Left 4 Dead 2', 'l4d2-server', 'Left 4 Dead 2 dedicated server', 'source',
                    steam_app_id=222860, cores=2, memory=4096, disk_size=25, ports=[27015], linuxgsm_name='l4d2server'),
    'hldm': _server('Half-Life Deathmatch', 'hldm-server', 'Half-Life Deathmatch dedicated server', 'source',
                    steam_app_id=90, cores=2, memory=2048, disk_size=15, ports=[27015], linuxgsm_name='hldmserver'),
    'hl2dm': _server('Half-Life 2: Deathmatch', 'hl2dm-server', 'Half-Life 2: Deathmatch dedicated server', 'source',
                     steam_app_id=232370, cores=2, memory=4096, disk_size=25, ports=[27015], linuxgsm_name='hl2dmserver'),
    'hldms': _server('Half-Life Deathmatch: Source', 'hldms-server', 'Half-Life Deathmatch: Source dedicated server', 'source',
                     steam_app_id=360, cores=2, memory=4096, disk_size=20, ports=[27015], linuxgsm_name='hldmsserver'),
    'blackmesa': _server('Black Mesa', 'blackmesa-server', 'Black Mesa Deathmatch dedicated server', 'source',
                         steam_app_id=346680, cores=4, memory=8192, disk_size=50, ports=[27015], linuxgsm_name='bmdmserver'),
    'svencoop': _server('Sven Co-op', 'svencoop-server', 'Sven Co-op dedicated server', 'source',
                        steam_app_id=276060, cores=2, memory=4096, disk_size=20, ports=[27015], linuxgsm_name='svenserver'),
    'dod': _server('Day of Defeat', 'dod-server', 'Day of Defeat dedicated server', 'source',
                   steam_app_id=30, cores=2, memory=2048, disk_size=15, ports=[27015], linuxgsm_name='dodserver'),
    'dods': _server('Day of Defeat: Source', 'dods-server', 'Day of Defeat: Source dedicated server', 'source',
                    steam_app_id=232290, cores=2, memory=4096, disk_size=20, ports=[27015], linuxgsm_name='dodsserver'),
    'fof': _server('Fistful of Frags', 'fof-server', 'Fistful of Frags dedicated server', 'source',
                   steam_app_id=295230, cores=2, memory=4096, disk_size=20, ports=[27015], linuxgsm_name='fofserver'),
    'synergy': _server('Synergy', 'synergy-server', 'Synergy co-op dedicated server', 'source',
                       steam_app_id=17520, cores=2, memory=4096, disk_size=20, ports=[27015]),
    'dmc': _server('Deathmatch Classic', 'dmc-server', 'Deathmatch Classic dedicated server', 'source',
                   steam_app_id=40, cores=2, memory=2048, disk_size=15, ports=[27015], linuxgsm_name='dmcserver'),
    'ricochet': _server('Ricochet', 'ricochet-server', 'Ricochet dedicated server', 'source',
                        steam_app_id=60, cores=2, memory=2048, disk_size=15, ports=[27015], linuxgsm_name='ricochetserver'),
    'opfor': _server('Opposing Force', 'opfor-server', 'Half-Life: Opposing Force dedicated server', 'source',
                     steam_app_id=50, cores=2, memory=2048, disk_size=15, ports=[27015], linuxgsm_name='opforserver'),
    'ahl': _server('Action Half-Life', 'ahl-server', 'Action Half-Life dedicated server', 'source',
                   cores=2, memory=2048, disk_size=15, ports=[27015], linuxgsm_name='ahlserver'),
    'ahl2': _server('Action: Source', 'ahl2-server', 'Action: Source dedicated server', 'source',
                    cores=2, memory=4096, disk_size=20, ports=[27015], linuxgsm_name='ahl2server'),
    'bb': _server('BrainBread', 'bb-server', 'BrainBread dedicated server', 'source',
                  cores=2, memory=2048, disk_size=15, ports=[27015], linuxgsm_name='bbserver'),
    'bb2': _server('BrainBread 2', 'bb2-server', 'BrainBread 2 dedicated server', 'source',
                   cores=2, memory=4096, disk_size=20, ports=[27015], linuxgsm_name='bb2server'),
    'dystopia': _server('Dystopia', 'dystopia-server', 'Dystopia dedicated server', 'source',
                        cores=2, memory=4096, disk_size=20, ports=[27015], linuxgsm_name='dysserver'),
    'empires': _server('Empires Mod', 'empires-server', 'Empires Mod dedicated server', 'source',
                       cores=2, memory=4096, disk_size=20, ports=[27015], linuxgsm_name='emserver'),
    'sfc': _server('SourceForts Classic', 'sfc-server', 'SourceForts Classic dedicated server', 'source',
                   cores=2, memory=4096, disk_size=20, ports=[27015], linuxgsm_name='sfcserver'),
    'ts': _server('The Specialists', 'ts-server', 'The Specialists dedicated server', 'source',
                  cores=2, memory=2048, disk_size=15, ports=[27015], linuxgsm_name='tsserver'),
    'vs': _server('Vampire Slayer', 'vs-server', 'Vampire Slayer dedicated server', 'source',
                  cores=2, memory=2048, disk_size=15, ports=[27015], linuxgsm_name='vsserver'),
    'zmr': _server('Zombie Master: Reborn', 'zmr-server', 'Zombie Master: Reborn dedicated server', 'source',
                   cores=2, memory=4096, disk_size=20, ports=[27015], linuxgsm_name='zmrserver'),
    'zps': _server('Zombie Panic! Source', 'zps-server', 'Zombie Panic! Source dedicated server', 'source',
                   cores=2, memory=4096, disk_size=20, ports=[27015], linuxgsm_name='zpsserver'),
    'pvkii': _server('Pirates Vikings & Knights II', 'pvkii-server', 'Pirates Vikings & Knights II dedicated server', 'source',
                     cores=2, memory=4096, disk_size=20, ports=[27015], linuxgsm_name='pvkiiserver'),

    # ============================================
    # SURVIVAL GAMES (45+ games)
    # ============================================
    'valheim': _server('Valheim', 'valheim-server', 'Valheim dedicated server', 'survival',
                       steam_app_id=896660, cores=4, memory=8192, disk_size=30, ports=[2456, 2457, 2458], linuxgsm_name='vhserver'),
    'rust': _server('Rust', 'rust-server', 'Rust dedicated server', 'survival',
                    steam_app_id=258550, cores=4, memory=16384, disk_size=50, ports=[28015, 28016], linuxgsm_name='rustserver'),
    'sdtd': _server('7 Days to Die', '7dtd-server', '7 Days to Die dedicated server', 'survival',
                    steam_app_id=294420, cores=4, memory=8192, disk_size=40, ports=[26900, 26901, 26902], linuxgsm_name='sdtdserver'),
    'pz': _server('Project Zomboid', 'pz-server', 'Project Zomboid dedicated server', 'survival',
                  steam_app_id=380870, cores=4, memory=8192, disk_size=30, ports=[16261, 16262], linuxgsm_name='pzserver'),
    'palworld': _server('Palworld', 'palworld-server', 'Palworld dedicated server', 'survival',
                        steam_app_id=2394010, cores=4, memory=16384, disk_size=50, ports=[8211], linuxgsm_name='pwserver'),
    'enshrouded': _server('Enshrouded', 'enshrouded-server', 'Enshrouded dedicated server', 'survival',
                          steam_app_id=2278520, cores=4, memory=16384, disk_size=50, ports=[15636, 15637]),
    'vrising': _server('V Rising', 'vrising-server', 'V Rising dedicated server', 'survival',
                       steam_app_id=1604030, cores=4, memory=8192, disk_size=30, ports=[9876, 9877]),
    'conanexiles': _server('Conan Exiles', 'conan-server', 'Conan Exiles dedicated server', 'survival',
                           steam_app_id=443030, cores=4, memory=8192, disk_size=50, ports=[7777, 7778, 27015]),
    'arksa': _server('ARK: Survival Ascended', 'arksa-server', 'ARK: Survival Ascended dedicated server', 'survival',
                     steam_app_id=2430930, cores=6, memory=32768, disk_size=100, ports=[7777, 7778, 27015]),
    'ark': _server('ARK: Survival Evolved', 'ark-server', 'ARK: Survival Evolved dedicated server', 'survival',
                   steam_app_id=376030, cores=4, memory=16384, disk_size=80, ports=[7777, 7778, 27015], linuxgsm_name='arkserver'),
    'dst': _server("Don't Starve Together", 'dst-server', "Don't Starve Together dedicated server", 'survival',
                   steam_app_id=343050, cores=2, memory=4096, disk_size=20, ports=[10999, 11000], linuxgsm_name='dstserver'),
    'sonsoftheforest': _server('Sons of the Forest', 'sotf-server', 'Sons of the Forest dedicated server', 'survival',
                               steam_app_id=2465200, cores=4, memory=8192, disk_size=30, ports=[8766, 27016]),
    'theforest': _server('The Forest', 'theforest-server', 'The Forest dedicated server', 'survival',
                         steam_app_id=556450, cores=2, memory=4096, disk_size=20, ports=[8766, 27016]),
    'barotrauma': _server('Barotrauma', 'barotrauma-server', 'Barotrauma dedicated server', 'survival',
                          steam_app_id=1026340, cores=2, memory=4096, disk_size=20, ports=[27015, 27016], linuxgsm_name='btserver'),
    'scum': _server('SCUM', 'scum-server', 'SCUM dedicated server', 'survival',
                    steam_app_id=3792580, cores=4, memory=16384, disk_size=50, ports=[7042, 7043]),
    'corekeeper': _server('Core Keeper', 'corekeeper-server', 'Core Keeper dedicated server', 'survival',
                          steam_app_id=1963720, cores=2, memory=4096, disk_size=20, ports=[27015, 27016], linuxgsm_name='ckserver'),
    'icarus': _server('Icarus', 'icarus-server', 'Icarus dedicated server', 'survival',
                      steam_app_id=2089300, cores=4, memory=8192, disk_size=40, ports=[17777]),
    'eco': _server('Eco', 'eco-server', 'Eco dedicated server', 'survival',
                   steam_app_id=382310, cores=2, memory=4096, disk_size=20, ports=[3000, 3001], linuxgsm_name='ecoserver'),
    'theisle': _server('The Isle', 'theisle-server', 'The Isle dedicated server', 'survival',
                       steam_app_id=412680, cores=4, memory=8192, disk_size=30, ports=[7777, 7778], linuxgsm_name='tiserver'),
    'dodr': _server('Day of Dragons', 'dodr-server', 'Day of Dragons dedicated server', 'survival',
                    cores=4, memory=8192, disk_size=30, ports=[7777, 7778], linuxgsm_name='dodrserver'),
    'hurtworld': _server('Hurtworld', 'hurtworld-server', 'Hurtworld dedicated server', 'survival',
                         steam_app_id=405100, cores=2, memory=4096, disk_size=20, ports=[12871, 12881], linuxgsm_name='hwserver'),
    'vintagestory': _server('Vintage Story', 'vintagestory-server', 'Vintage Story dedicated server', 'survival',
                            cores=2, memory=4096, disk_size=20, ports=[42420], linuxgsm_name='vintsserver'),
    'craftopia': _server('Craftopia', 'craftopia-server', 'Craftopia dedicated server', 'survival',
                         steam_app_id=1307550, cores=2, memory=4096, disk_size=20, ports=[6587], linuxgsm_name='ctserver'),
    'empyrion': _server('Empyrion Galactic Survival', 'empyrion-server', 'Empyrion Galactic Survival dedicated server', 'survival',
                        steam_app_id=530870, cores=4, memory=8192, disk_size=30, ports=[30000, 30001]),
    'cryofall': _server('CryoFall', 'cryofall-server', 'CryoFall dedicated server', 'survival',
                        steam_app_id=829590, cores=2, memory=4096, disk_size=20, ports=[6000]),
    'longvinter': _server('Longvinter', 'longvinter-server', 'Longvinter dedicated server', 'survival',
                          steam_app_id=1628750, cores=2, memory=4096, disk_size=20, ports=[7777]),
    'nightingale': _server('Nightingale', 'nightingale-server', 'Nightingale dedicated server', 'survival',
                           steam_app_id=1928980, cores=4, memory=8192, disk_size=40, ports=[7777]),
    'thefront': _server('The Front', 'thefront-server', 'The Front dedicated server', 'survival',
                        steam_app_id=2285150, cores=4, memory=8192, disk_size=40, ports=[25010, 25011], linuxgsm_name='tfserver'),
    'mythofempires': _server('Myth of Empires', 'mythofempires-server', 'Myth of Empires dedicated server', 'survival',
                             steam_app_id=1371580, cores=4, memory=16384, disk_size=50, ports=[12888, 12889]),
    'lastoasis': _server('Last Oasis', 'lastoasis-server', 'Last Oasis dedicated server', 'survival',
                         steam_app_id=920720, cores=4, memory=8192, disk_size=30, ports=[5555, 5556]),
    'noonesurvived': _server('No One Survived', 'noonesurvived-server', 'No One Survived dedicated server', 'survival',
                             steam_app_id=1963370, cores=2, memory=4096, disk_size=20, ports=[7777]),
    'soulmask': _server('Soulmask', 'soulmask-server', 'Soulmask dedicated server', 'survival',
                        steam_app_id=3040080, cores=4, memory=8192, disk_size=40, ports=[7777, 7778], linuxgsm_name='smserver'),
    'humanitz': _server('HumanitZ', 'humanitz-server', 'HumanitZ dedicated server', 'survival',
                        steam_app_id=2740380, cores=2, memory=4096, disk_size=20, ports=[7777], linuxgsm_name='hzserver'),
    'stn': _server('Survive the Nights', 'stn-server', 'Survive the Nights dedicated server', 'survival',
                   cores=2, memory=4096, disk_size=20, ports=[7777], linuxgsm_name='stnserver'),
    'abioticfactor': _server('Abiotic Factor', 'abioticfactor-server', 'Abiotic Factor dedicated server', 'survival',
                             cores=2, memory=4096, disk_size=20, ports=[7777]),
    'frozenflame': _server('Frozen Flame', 'frozenflame-server', 'Frozen Flame dedicated server', 'survival',
                           cores=4, memory=8192, disk_size=30, ports=[7777]),
    'deadmatter': _server('Dead Matter', 'deadmatter-server', 'Dead Matter dedicated server', 'survival',
                          cores=4, memory=8192, disk_size=40, ports=[7777]),
    'deadpoly': _server('Deadpoly', 'deadpoly-server', 'Deadpoly dedicated server', 'survival',
                        cores=2, memory=4096, disk_size=20, ports=[7777]),
    'nightofthedead': _server('Night of the Dead', 'notd-server', 'Night of the Dead dedicated server', 'survival',
                              cores=2, memory=4096, disk_size=20, ports=[7777]),
    'plainsofpain': _server('Plains of Pain', 'pop-server', 'Plains of Pain dedicated server', 'survival',
                            cores=2, memory=4096, disk_size=20, ports=[7777]),
    'pixark': _server('PixARK', 'pixark-server', 'PixARK dedicated server', 'survival',
                      cores=2, memory=4096, disk_size=30, ports=[7777]),
    'aska': _server('ASKA', 'aska-server', 'ASKA dedicated server', 'survival',
                    cores=2, memory=4096, disk_size=20, ports=[7777]),
    'exfil': _server('Exfil', 'exfil-server', 'Exfil dedicated server', 'survival',
                     cores=2, memory=4096, disk_size=20, ports=[7777]),

    # ============================================
    # MILITARY SIMULATION (15+ games)
    # ============================================
    'dayz': _server('DayZ', 'dayz-server', 'DayZ dedicated server', 'milsim',
                    steam_app_id=223350, cores=4, memory=8192, disk_size=50, ports=[2302, 2303, 27016], linuxgsm_name='dayzserver'),
    'dayzexp': _server('DayZ Experimental', 'dayzexp-server', 'DayZ Experimental dedicated server', 'milsim',
                       cores=4, memory=8192, disk_size=50, ports=[2302, 2303, 27016]),
    'arma3': _server('ARMA 3', 'arma3-server', 'ARMA 3 dedicated server', 'milsim',
                     steam_app_id=233780, cores=4, memory=8192, disk_size=60, ports=[2302, 2303, 2304], linuxgsm_name='arma3server'),
    'armareforger': _server('Arma Reforger', 'armareforger-server', 'Arma Reforger dedicated server', 'milsim',
                            steam_app_id=1874900, cores=4, memory=8192, disk_size=40, ports=[2001], linuxgsm_name='armarserver'),
    'squad': _server('Squad', 'squad-server', 'Squad dedicated server', 'milsim',
                     steam_app_id=403240, cores=4, memory=8192, disk_size=50, ports=[7787, 7788, 27165], linuxgsm_name='squadserver'),
    'squad44': _server('Squad 44', 'squad44-server', 'Squad 44 (Post Scriptum) dedicated server', 'milsim',
                       steam_app_id=746200, cores=4, memory=8192, disk_size=50, ports=[10027], linuxgsm_name='squad44server'),
    'hellletloose': _server('Hell Let Loose', 'hellletloose-server', 'Hell Let Loose dedicated server', 'milsim',
                            steam_app_id=1348460, cores=4, memory=16384, disk_size=50, ports=[7777, 7778, 27015]),
    'insurgencysandstorm': _server('Insurgency: Sandstorm', 'inss-server', 'Insurgency: Sandstorm dedicated server', 'milsim',
                                   steam_app_id=581330, cores=4, memory=8192, disk_size=40, ports=[27102, 27131], linuxgsm_name='inssserver'),
    'insurgency': _server('Insurgency', 'insurgency-server', 'Insurgency dedicated server', 'milsim',
                          steam_app_id=237410, cores=2, memory=4096, disk_size=20, ports=[27015], linuxgsm_name='insserver'),
    'dayofinfamy': _server('Day of Infamy', 'doi-server', 'Day of Infamy dedicated server', 'milsim',
                           steam_app_id=462310, cores=2, memory=4096, disk_size=20, ports=[27015], linuxgsm_name='doiserver'),
    'ohd': _server('Operation: Harsh Doorstop', 'ohd-server', 'Operation: Harsh Doorstop dedicated server', 'milsim',
                   cores=4, memory=8192, disk_size=40, ports=[7777], linuxgsm_name='ohdserver'),
    'groundbranch': _server('Ground Branch', 'groundbranch-server', 'Ground Branch dedicated server', 'milsim',
                            cores=2, memory=4096, disk_size=20, ports=[7777]),
    'risingstorm2': _server('Rising Storm 2: Vietnam', 'rs2-server', 'Rising Storm 2: Vietnam dedicated server', 'milsim',
                            cores=4, memory=8192, disk_size=40, ports=[7777, 7778, 27015]),

    # ============================================
    # SANDBOX & BUILDING (30+ games)
    # ============================================
    'minecraft': _server('Minecraft Java', 'minecraft-server', 'Minecraft Java Edition dedicated server', 'sandbox',
                         cores=4, memory=8192, disk_size=30, ports=[25565], linuxgsm_name='mcserver'),
    'minecraftbedrock': _server('Minecraft Bedrock', 'mcbedrock-server', 'Minecraft Bedrock dedicated server', 'sandbox',
                                cores=2, memory=4096, disk_size=20, ports=[19132], linuxgsm_name='mcbserver'),
    'papermc': _server('PaperMC', 'papermc-server', 'PaperMC Minecraft server', 'sandbox',
                       cores=4, memory=8192, disk_size=30, ports=[25565], linuxgsm_name='pmcserver'),
    'velocitymc': _server('Velocity Proxy MC', 'velocity-server', 'Velocity Minecraft proxy', 'sandbox',
                          cores=2, memory=2048, disk_size=10, ports=[25577], linuxgsm_name='vpmcserver'),
    'waterfallmc': _server('WaterfallMC', 'waterfall-server', 'WaterfallMC Minecraft proxy', 'sandbox',
                           cores=2, memory=2048, disk_size=10, ports=[25577], linuxgsm_name='wmcserver'),
    'terraria': _server('Terraria', 'terraria-server', 'Terraria dedicated server', 'sandbox',
                        steam_app_id=105600, cores=2, memory=4096, disk_size=15, ports=[7777], linuxgsm_name='terrariaserver'),
    'starbound': _server('Starbound', 'starbound-server', 'Starbound dedicated server', 'sandbox',
                         steam_app_id=211820, cores=2, memory=4096, disk_size=20, ports=[21025], linuxgsm_name='sbserver'),
    'openstarbound': _server('OpenStarbound', 'openstarbound-server', 'OpenStarbound dedicated server', 'sandbox',
                             cores=2, memory=4096, disk_size=20, ports=[21025]),
    'factorio': _server('Factorio', 'factorio-server', 'Factorio dedicated server', 'sandbox',
                        steam_app_id=427520, cores=2, memory=4096, disk_size=20, ports=[34197], linuxgsm_name='fctrserver'),
    'satisfactory': _server('Satisfactory', 'satisfactory-server', 'Satisfactory dedicated server', 'sandbox',
                            steam_app_id=1690800, cores=4, memory=8192, disk_size=40, ports=[7777, 15000, 15777], linuxgsm_name='sfserver'),
    'spaceengineers': _server('Space Engineers', 'spaceengineers-server', 'Space Engineers dedicated server', 'sandbox',
                              steam_app_id=298740, cores=4, memory=8192, disk_size=30, ports=[27016]),
    'stationeers': _server('Stationeers', 'stationeers-server', 'Stationeers dedicated server', 'sandbox',
                           steam_app_id=544550, cores=2, memory=4096, disk_size=20, ports=[27500, 27015], linuxgsm_name='stserver'),
    'avorion': _server('Avorion', 'avorion-server', 'Avorion dedicated server', 'sandbox',
                       steam_app_id=565060, cores=2, memory=4096, disk_size=20, ports=[27000, 27003, 27020, 27021], linuxgsm_name='avserver'),
    'colonysurvival': _server('Colony Survival', 'colonysurvival-server', 'Colony Survival dedicated server', 'sandbox',
                              steam_app_id=366090, cores=2, memory=4096, disk_size=20, ports=[27016, 27017], linuxgsm_name='colserver'),
    'risingworld': _server('Rising World', 'risingworld-server', 'Rising World dedicated server', 'sandbox',
                           steam_app_id=324080, cores=2, memory=4096, disk_size=20, ports=[4255], linuxgsm_name='rwserver'),
    'wurm': _server('Wurm Unlimited', 'wurm-server', 'Wurm Unlimited dedicated server', 'sandbox',
                    steam_app_id=366220, cores=2, memory=4096, disk_size=20, ports=[3724], linuxgsm_name='wurmserver'),
    'astroneer': _server('Astroneer', 'astroneer-server', 'Astroneer dedicated server', 'sandbox',
                         steam_app_id=728470, cores=2, memory=4096, disk_size=20, ports=[8777]),
    'openttd': _server('OpenTTD', 'openttd-server', 'OpenTTD dedicated server', 'sandbox',
                       steam_app_id=1536610, cores=1, memory=1024, disk_size=5, ports=[3979]),
    'minetest': _server('Minetest', 'minetest-server', 'Minetest dedicated server', 'sandbox',
                        cores=2, memory=2048, disk_size=10, ports=[30000]),
    'creativerse': _server('Creativerse', 'creativerse-server', 'Creativerse dedicated server', 'sandbox',
                           cores=2, memory=4096, disk_size=20, ports=[26900]),
    'cubicodes': _server('Cubic Odyssey', 'cubicodyssey-server', 'Cubic Odyssey dedicated server', 'sandbox',
                         cores=2, memory=4096, disk_size=20, ports=[7777]),
    'portalknights': _server('Portal Knights', 'portalknights-server', 'Portal Knights dedicated server', 'sandbox',
                             cores=2, memory=4096, disk_size=20, ports=[7777]),
    'stonehearth': _server('Stonehearth', 'stonehearth-server', 'Stonehearth dedicated server', 'sandbox',
                           cores=2, memory=4096, disk_size=20, ports=[7777]),
    'astrocolony': _server('Astro Colony', 'astrocolony-server', 'Astro Colony dedicated server', 'sandbox',
                           cores=2, memory=4096, disk_size=20, ports=[7777]),
    'openrct2': _server('OpenRCT2', 'openrct2-server', 'OpenRCT2 dedicated server', 'sandbox',
                        cores=1, memory=1024, disk_size=5, ports=[11753]),

    # ============================================
    # RACING & SIMULATION (10 games)
    # ============================================
    'assettocorsa': _server('Assetto Corsa', 'assettocorsa-server', 'Assetto Corsa dedicated server', 'racing',
                            steam_app_id=302550, cores=2, memory=4096, disk_size=30, ports=[9600, 8081], linuxgsm_name='acserver'),
    'acc': _server('Assetto Corsa Competizione', 'acc-server', 'Assetto Corsa Competizione dedicated server', 'racing',
                   steam_app_id=805550, cores=4, memory=8192, disk_size=40, ports=[9231]),
    'ets2': _server('Euro Truck Simulator 2', 'ets2-server', 'Euro Truck Simulator 2 dedicated server', 'racing',
                    steam_app_id=227300, cores=2, memory=4096, disk_size=20, ports=[27015], linuxgsm_name='ets2server'),
    'ats': _server('American Truck Simulator', 'ats-server', 'American Truck Simulator dedicated server', 'racing',
                   steam_app_id=270880, cores=2, memory=4096, disk_size=20, ports=[27015], linuxgsm_name='atsserver'),
    'beammp': _server('BeamMP', 'beammp-server', 'BeamMP (BeamNG.drive) dedicated server', 'racing',
                      cores=2, memory=4096, disk_size=20, ports=[30814]),
    'projectcars': _server('Project Cars', 'pcars-server', 'Project Cars dedicated server', 'racing',
                           cores=2, memory=4096, disk_size=20, ports=[9000], linuxgsm_name='pcserver'),
    'projectcars2': _server('Project Cars 2', 'pcars2-server', 'Project Cars 2 dedicated server', 'racing',
                            cores=2, memory=4096, disk_size=20, ports=[9000], linuxgsm_name='pc2server'),
    'mxbikes': _server('MX Bikes', 'mxbikes-server', 'MX Bikes dedicated server', 'racing',
                       cores=2, memory=4096, disk_size=20, ports=[7777]),

    # ============================================
    # ARENA & COMPETITIVE (30+ games)
    # ============================================
    'quake3': _server('Quake III Arena', 'quake3-server', 'Quake III Arena dedicated server', 'arena',
                      cores=1, memory=1024, disk_size=10, ports=[27960], linuxgsm_name='q3server'),
    'quake2': _server('Quake 2', 'quake2-server', 'Quake 2 dedicated server', 'arena',
                      cores=1, memory=1024, disk_size=10, ports=[27910], linuxgsm_name='q2server'),
    'quake4': _server('Quake 4', 'quake4-server', 'Quake 4 dedicated server', 'arena',
                      cores=2, memory=2048, disk_size=15, ports=[28004], linuxgsm_name='q4server'),
    'quakelive': _server('Quake Live', 'quakelive-server', 'Quake Live dedicated server', 'arena',
                         steam_app_id=349090, cores=1, memory=2048, disk_size=15, ports=[27960], linuxgsm_name='qlserver'),
    'quakeworld': _server('Quake World', 'quakeworld-server', 'Quake World dedicated server', 'arena',
                          cores=1, memory=1024, disk_size=5, ports=[27500], linuxgsm_name='qwserver'),
    'xonotic': _server('Xonotic', 'xonotic-server', 'Xonotic dedicated server', 'arena',
                       cores=2, memory=2048, disk_size=10, ports=[26000], linuxgsm_name='xntserver'),
    'warfork': _server('Warfork', 'warfork-server', 'Warfork dedicated server', 'arena',
                       cores=2, memory=2048, disk_size=10, ports=[44400], linuxgsm_name='wfserver'),
    'ut99': _server('Unreal Tournament 99', 'ut99-server', 'Unreal Tournament 99 dedicated server', 'arena',
                    cores=1, memory=1024, disk_size=10, ports=[7777], linuxgsm_name='ut99server'),
    'ut2004': _server('Unreal Tournament 2004', 'ut2004-server', 'Unreal Tournament 2004 dedicated server', 'arena',
                      cores=2, memory=2048, disk_size=15, ports=[7777], linuxgsm_name='ut2k4server'),
    'ut3': _server('Unreal Tournament 3', 'ut3-server', 'Unreal Tournament 3 dedicated server', 'arena',
                   cores=2, memory=4096, disk_size=20, ports=[7777], linuxgsm_name='ut3server'),
    'chivalry': _server('Chivalry: Medieval Warfare', 'chivalry-server', 'Chivalry: Medieval Warfare dedicated server', 'arena',
                        steam_app_id=220070, cores=2, memory=4096, disk_size=20, ports=[7777], linuxgsm_name='cmwserver'),
    'mordhau': _server('MORDHAU', 'mordhau-server', 'MORDHAU dedicated server', 'arena',
                       steam_app_id=629800, cores=4, memory=8192, disk_size=40, ports=[7777, 15000, 27015], linuxgsm_name='mhserver'),
    'pavlov': _server('Pavlov VR', 'pavlov-server', 'Pavlov VR dedicated server', 'arena',
                      steam_app_id=622970, cores=2, memory=4096, disk_size=20, ports=[7777], linuxgsm_name='pvrserver'),
    'teeworlds': _server('Teeworlds', 'teeworlds-server', 'Teeworlds dedicated server', 'arena',
                         cores=1, memory=512, disk_size=5, ports=[8303], linuxgsm_name='twserver'),
    'soldat': _server('Soldat', 'soldat-server', 'Soldat dedicated server', 'arena',
                      cores=1, memory=512, disk_size=5, ports=[23073], linuxgsm_name='solserver'),
    'iofootball': _server('IOSoccer', 'iofootball-server', 'IOSoccer dedicated server', 'arena',
                          cores=2, memory=2048, disk_size=15, ports=[27015], linuxgsm_name='iosserver'),
    'bladesymphony': _server('Blade Symphony', 'bladesymphony-server', 'Blade Symphony dedicated server', 'arena',
                             cores=2, memory=2048, disk_size=15, ports=[27015], linuxgsm_name='bsserver'),
    'ballisticoverkill': _server('Ballistic Overkill', 'bo-server', 'Ballistic Overkill dedicated server', 'arena',
                                 cores=2, memory=2048, disk_size=15, ports=[27015], linuxgsm_name='boserver'),
    'battalion': _server('BATTALION: Legacy', 'battalion-server', 'BATTALION: Legacy dedicated server', 'arena',
                         cores=2, memory=4096, disk_size=20, ports=[7777], linuxgsm_name='btlserver'),
    'doubleaction': _server('Double Action: Boogaloo', 'doubleaction-server', 'Double Action: Boogaloo dedicated server', 'arena',
                            cores=2, memory=2048, disk_size=15, ports=[27015], linuxgsm_name='dabserver'),
    'stickybots': _server('StickyBots', 'stickybots-server', 'StickyBots dedicated server', 'arena',
                          cores=2, memory=2048, disk_size=15, ports=[27015], linuxgsm_name='sbotsserver'),
    'basedefense': _server('Base Defense', 'basedefense-server', 'Base Defense dedicated server', 'arena',
                           cores=2, memory=2048, disk_size=15, ports=[27015], linuxgsm_name='bdserver'),
    'sauerbraten': _server('Cube 2: Sauerbraten', 'sauerbraten-server', 'Cube 2: Sauerbraten dedicated server', 'arena',
                           cores=1, memory=1024, disk_size=5, ports=[28785]),
    'tremulous': _server('Tremulous', 'tremulous-server', 'Tremulous dedicated server', 'arena',
                         cores=1, memory=1024, disk_size=5, ports=[30720]),
    'openra': _server('OpenRA', 'openra-server', 'OpenRA dedicated server', 'arena',
                      cores=1, memory=1024, disk_size=5, ports=[1234]),

    # ============================================
    # CO-OP & MULTIPLAYER (25+ games)
    # ============================================
    'nmrih': _server('No More Room in Hell', 'nmrih-server', 'No More Room in Hell dedicated server', 'coop',
                     steam_app_id=317670, cores=2, memory=4096, disk_size=20, ports=[27015], linuxgsm_name='nmrihserver'),
    'ns': _server('Natural Selection', 'ns-server', 'Natural Selection dedicated server', 'coop',
                  cores=2, memory=2048, disk_size=15, ports=[27015], linuxgsm_name='nsserver'),
    'ns2': _server('Natural Selection 2', 'ns2-server', 'Natural Selection 2 dedicated server', 'coop',
                   steam_app_id=4940, cores=4, memory=4096, disk_size=25, ports=[27015, 27016], linuxgsm_name='ns2server'),
    'ns2c': _server('NS2: Combat', 'ns2c-server', 'NS2: Combat dedicated server', 'coop',
                    cores=2, memory=4096, disk_size=20, ports=[27015], linuxgsm_name='ns2cserver'),
    'scpsl': _server('SCP: Secret Laboratory', 'scpsl-server', 'SCP: Secret Laboratory dedicated server', 'coop',
                     steam_app_id=996560, cores=2, memory=4096, disk_size=20, ports=[7777], linuxgsm_name='scpslserver'),
    'scpslsm': _server('SCP: Secret Laboratory ServerMod', 'scpslsm-server', 'SCP:SL with ServerMod', 'coop',
                       cores=2, memory=4096, disk_size=20, ports=[7777], linuxgsm_name='scpslsmserver'),
    'towerunite': _server('Tower Unite', 'towerunite-server', 'Tower Unite dedicated server', 'coop',
                          steam_app_id=439660, cores=2, memory=4096, disk_size=20, ports=[27015], linuxgsm_name='tuserver'),
    'riskofrain2': _server('Risk of Rain 2', 'ror2-server', 'Risk of Rain 2 dedicated server', 'coop',
                           steam_app_id=1180760, cores=2, memory=4096, disk_size=20, ports=[27015]),
    'rimworldtogether': _server('Rimworld Together', 'rimworldtogether-server', 'Rimworld Together dedicated server', 'coop',
                                cores=2, memory=4096, disk_size=20, ports=[25555]),
    'pathoftitans': _server('Path of Titans', 'pathoftitans-server', 'Path of Titans dedicated server', 'coop',
                            cores=4, memory=8192, disk_size=40, ports=[7777]),
    'mindustry': _server('Mindustry', 'mindustry-server', 'Mindustry dedicated server', 'coop',
                         steam_app_id=1127400, cores=1, memory=1024, disk_size=10, ports=[6567]),
    'necesse': _server('Necesse', 'necesse-server', 'Necesse dedicated server', 'coop',
                       cores=2, memory=4096, disk_size=15, ports=[14159], linuxgsm_name='necserver'),
    'nucleardawn': _server('Nuclear Dawn', 'nucleardawn-server', 'Nuclear Dawn dedicated server', 'coop',
                           cores=2, memory=4096, disk_size=20, ports=[27015], linuxgsm_name='ndserver'),
    'codenamecure': _server('Codename CURE', 'codenamecure-server', 'Codename CURE dedicated server', 'coop',
                            cores=2, memory=4096, disk_size=20, ports=[27015], linuxgsm_name='ccserver'),
    'hypercharge': _server('HYPERCHARGE: Unboxed', 'hypercharge-server', 'HYPERCHARGE: Unboxed dedicated server', 'coop',
                           cores=2, memory=4096, disk_size=20, ports=[7777], linuxgsm_name='hcuserver'),
    'alienswarm': _server('Alien Swarm: Reactive Drop', 'alienswarm-server', 'Alien Swarm: Reactive Drop dedicated server', 'coop',
                          cores=2, memory=4096, disk_size=20, ports=[27015]),
    'clonehero': _server('Clone Hero', 'clonehero-server', 'Clone Hero dedicated server', 'coop',
                         cores=1, memory=2048, disk_size=10, ports=[14242]),
    'beastsofbermuda': _server('Beasts of Bermuda', 'bob-server', 'Beasts of Bermuda dedicated server', 'coop',
                               cores=4, memory=8192, disk_size=30, ports=[7777]),

    # ============================================
    # ROLEPLAY (12+ games)
    # ============================================
    'fivem': _server('FiveM', 'fivem-server', 'FiveM (GTA V) dedicated server', 'roleplay',
                     cores=4, memory=8192, disk_size=50, ports=[30120]),
    'altv': _server('alt:V', 'altv-server', 'alt:V (GTA V) dedicated server', 'roleplay',
                    cores=4, memory=8192, disk_size=40, ports=[7788]),
    'redm': _server('RedM', 'redm-server', 'RedM (Red Dead Redemption 2) dedicated server', 'roleplay',
                    cores=4, memory=8192, disk_size=50, ports=[30120]),
    'mta': _server('Multi Theft Auto', 'mta-server', 'Multi Theft Auto dedicated server', 'roleplay',
                   cores=2, memory=4096, disk_size=20, ports=[22003, 22005, 22126], linuxgsm_name='mtaserver'),
    'ragemp': _server('RAGE:MP', 'ragemp-server', 'RAGE:MP (GTA V) dedicated server', 'roleplay',
                      cores=4, memory=8192, disk_size=40, ports=[22005]),
    'samp': _server('SA-MP', 'samp-server', 'San Andreas Multiplayer dedicated server', 'roleplay',
                    cores=1, memory=2048, disk_size=10, ports=[7777], linuxgsm_name='sampserver'),
    'jc2mp': _server('Just Cause 2 MP', 'jc2mp-server', 'Just Cause 2 Multiplayer dedicated server', 'roleplay',
                     cores=2, memory=4096, disk_size=20, ports=[7777], linuxgsm_name='jc2server'),
    'jc3mp': _server('Just Cause 3 MP', 'jc3mp-server', 'Just Cause 3 Multiplayer dedicated server', 'roleplay',
                     cores=2, memory=4096, disk_size=20, ports=[7777], linuxgsm_name='jc3server'),
    'onset': _server('Onset', 'onset-server', 'Onset dedicated server', 'roleplay',
                     cores=2, memory=4096, disk_size=20, ports=[7777], linuxgsm_name='onsetserver'),

    # ============================================
    # CLASSIC GAMES (30+ games)
    # ============================================
    'kf': _server('Killing Floor', 'kf-server', 'Killing Floor dedicated server', 'classic',
                  steam_app_id=215360, cores=2, memory=2048, disk_size=15, ports=[7707, 7708, 28852], linuxgsm_name='kfserver'),
    'kf2': _server('Killing Floor 2', 'kf2-server', 'Killing Floor 2 dedicated server', 'classic',
                   steam_app_id=232130, cores=2, memory=4096, disk_size=25, ports=[7777, 27015], linuxgsm_name='kf2server'),
    'cod': _server('Call of Duty', 'cod-server', 'Call of Duty dedicated server', 'classic',
                   cores=1, memory=1024, disk_size=10, ports=[28960], linuxgsm_name='codserver'),
    'cod2': _server('Call of Duty 2', 'cod2-server', 'Call of Duty 2 dedicated server', 'classic',
                    cores=1, memory=1024, disk_size=10, ports=[28960], linuxgsm_name='cod2server'),
    'cod4': _server('Call of Duty 4: MW', 'cod4-server', 'Call of Duty 4: Modern Warfare dedicated server', 'classic',
                    cores=2, memory=2048, disk_size=15, ports=[28960], linuxgsm_name='cod4server'),
    'coduo': _server('Call of Duty: United Offensive', 'coduo-server', 'Call of Duty: United Offensive dedicated server', 'classic',
                     cores=1, memory=1024, disk_size=10, ports=[28960], linuxgsm_name='coduoserver'),
    'codwaw': _server('Call of Duty: World at War', 'codwaw-server', 'Call of Duty: World at War dedicated server', 'classic',
                      cores=2, memory=2048, disk_size=15, ports=[28960], linuxgsm_name='codwawserver'),
    'bf1942': _server('Battlefield 1942', 'bf1942-server', 'Battlefield 1942 dedicated server', 'classic',
                      cores=1, memory=1024, disk_size=10, ports=[14567, 14690, 23000], linuxgsm_name='bf1942server'),
    'bfv': _server('Battlefield: Vietnam', 'bfv-server', 'Battlefield: Vietnam dedicated server', 'classic',
                   cores=1, memory=1024, disk_size=10, ports=[15567], linuxgsm_name='bfvserver'),
    'mohaa': _server('Medal of Honor: Allied Assault', 'mohaa-server', 'Medal of Honor: Allied Assault dedicated server', 'classic',
                     cores=1, memory=1024, disk_size=10, ports=[12203, 12300], linuxgsm_name='mohaaserver'),
    'rtcw': _server('Return to Castle Wolfenstein', 'rtcw-server', 'Return to Castle Wolfenstein dedicated server', 'classic',
                    cores=1, memory=1024, disk_size=10, ports=[27960], linuxgsm_name='rtcwserver'),
    'wet': _server('Wolfenstein: Enemy Territory', 'wet-server', 'Wolfenstein: Enemy Territory dedicated server', 'classic',
                   cores=1, memory=1024, disk_size=10, ports=[27960], linuxgsm_name='wetserver'),
    'etl': _server('ET: Legacy', 'etl-server', 'ET: Legacy dedicated server', 'classic',
                   cores=1, memory=1024, disk_size=10, ports=[27960], linuxgsm_name='etlserver'),
    'sof2': _server('Soldier of Fortune 2', 'sof2-server', 'Soldier of Fortune 2 dedicated server', 'classic',
                    cores=1, memory=1024, disk_size=10, ports=[28910], linuxgsm_name='sof2server'),
    'unturned': _server('Unturned', 'unturned-server', 'Unturned dedicated server', 'classic',
                        steam_app_id=304930, cores=2, memory=4096, disk_size=20, ports=[27015, 27016], linuxgsm_name='untserver'),
    'jk2': _server('Jedi Knight II: Jedi Outcast', 'jk2-server', 'Jedi Knight II: Jedi Outcast dedicated server', 'classic',
                   cores=1, memory=1024, disk_size=10, ports=[28070], linuxgsm_name='jk2server'),
    'jka': _server('Jedi Academy', 'jka-server', 'Jedi Academy dedicated server', 'classic',
                   cores=1, memory=1024, disk_size=10, ports=[29070]),
    'doom2': _server('Doom 2', 'doom2-server', 'Doom 2 dedicated server', 'classic',
                     cores=1, memory=512, disk_size=5, ports=[5029]),
    'ro': _server('Red Orchestra: Ostfront', 'ro-server', 'Red Orchestra: Ostfront dedicated server', 'classic',
                  cores=2, memory=2048, disk_size=15, ports=[7757, 7758], linuxgsm_name='roserver'),
    'blackwake': _server('Blackwake', 'blackwake-server', 'Blackwake dedicated server', 'classic',
                         cores=2, memory=4096, disk_size=20, ports=[25001]),
    'brokeprotocol': _server('Broke Protocol', 'brokeprotocol-server', 'Broke Protocol dedicated server', 'classic',
                             cores=2, memory=4096, disk_size=20, ports=[5557]),
    'reignofkings': _server('Reign of Kings', 'reignofkings-server', 'Reign of Kings dedicated server', 'classic',
                            cores=2, memory=4096, disk_size=20, ports=[7350]),
    'eyedivine': _server('Eye: Divine Cybermancy', 'eyedivine-server', 'Eye: Divine Cybermancy dedicated server', 'classic',
                         cores=2, memory=2048, disk_size=15, ports=[27015]),
    'lotrmoria': _server('LOTR: Return to Moria', 'lotrmoria-server', 'LOTR: Return to Moria dedicated server', 'classic',
                         cores=4, memory=8192, disk_size=40, ports=[7777]),

    # ============================================
    # VOICE & COMMUNICATION (2 apps)
    # ============================================
    'ts3': _server('TeamSpeak 3', 'ts3-server', 'TeamSpeak 3 voice server', 'voice',
                   cores=1, memory=1024, disk_size=5, ports=[9987, 10011, 30033], linuxgsm_name='ts3server'),
    'mumble': _server('Mumble', 'mumble-server', 'Mumble voice server', 'voice',
                      cores=1, memory=1024, disk_size=5, ports=[64738]),

    # ============================================
    # RPG & TABLETOP (6 games)
    # ============================================
    'foundryvtt': _server('Foundry VTT', 'foundryvtt-server', 'Foundry Virtual Tabletop', 'rpg',
                          cores=2, memory=4096, disk_size=20, ports=[30000]),
    'sapiens': _server('Sapiens', 'sapiens-server', 'Sapiens dedicated server', 'rpg',
                       cores=2, memory=4096, disk_size=20, ports=[7777]),
    'wartales': _server('Wartales', 'wartales-server', 'Wartales dedicated server', 'rpg',
                        cores=2, memory=4096, disk_size=20, ports=[7777]),
    'stellaris': _server('Stellaris', 'stellaris-server', 'Stellaris dedicated server', 'rpg',
                         cores=4, memory=8192, disk_size=30, ports=[23243]),
    'dota2': _server('Dota 2', 'dota2-server', 'Dota 2 custom game server', 'rpg',
                     cores=4, memory=8192, disk_size=40, ports=[27015]),
    'subnautica': _server('Subnautica Nitrox', 'subnautica-server', 'Subnautica Nitrox multiplayer server', 'rpg',
                          cores=2, memory=4096, disk_size=20, ports=[11000]),
    'thrive': _server('Thrive', 'thrive-server', 'Thrive multiplayer server', 'rpg',
                      cores=2, memory=4096, disk_size=15, ports=[7777]),

    # ============================================
    # MMO EMULATORS (6 games)
    # ============================================
    'azerothcore': _server('WoW (AzerothCore)', 'azerothcore-server', 'World of Warcraft 3.3.5a private server', 'mmo',
                           cores=4, memory=8192, disk_size=50, ports=[3724, 8085]),
    'trinitycore': _server('WoW (TrinityCore)', 'trinitycore-server', 'World of Warcraft private server', 'mmo',
                           cores=4, memory=8192, disk_size=50, ports=[3724, 8085]),
    'swgemu': _server('SWGEmu', 'swgemu-server', 'Star Wars Galaxies emulator', 'mmo',
                      cores=4, memory=8192, disk_size=50, ports=[44419, 44453, 44463]),
    'swglegends': _server('SWG: Legends', 'swglegends-server', 'Star Wars Galaxies Legends', 'mmo',
                          cores=4, memory=8192, disk_size=50, ports=[44419]),
    'cityofheroes': _server('City of Heroes', 'coh-server', 'City of Heroes private server', 'mmo',
                            cores=4, memory=8192, disk_size=50, ports=[2104]),
    'impostor': _server('Impostor (Among Us)', 'impostor-server', 'Impostor Among Us private server', 'mmo',
                        cores=1, memory=1024, disk_size=5, ports=[22023]),

    # ============================================
    # SERVER MANAGEMENT PANELS (4 tools)
    # ============================================
    'pterodactyl': _server('Pterodactyl', 'pterodactyl-server', 'Pterodactyl game server panel', 'management',
                           cores=4, memory=4096, disk_size=30, ports=[80, 443, 8080]),
    'craftycont': _server('Crafty Controller', 'crafty-server', 'Crafty Controller for Minecraft', 'management',
                          cores=2, memory=4096, disk_size=20, ports=[8443, 8123]),
    'amp': _server('AMP (CubeCoders)', 'amp-server', 'AMP game server panel', 'management',
                   cores=2, memory=4096, disk_size=30, ports=[8080]),
}

def get_server_by_key(key):
    """Get a server configuration by its key."""
    return GAME_SERVERS.get(key)

def get_servers_by_category(category):
    """Get all servers in a category."""
    return {k: v for k, v in GAME_SERVERS.items() if v.get('category') == category}

def get_all_categories():
    """Get all category definitions."""
    return CATEGORIES

def get_all_servers():
    """Get all server configurations."""
    return GAME_SERVERS

def search_servers(query):
    """Search servers by name or description."""
    query = query.lower()
    results = {}
    for key, server in GAME_SERVERS.items():
        if query in key.lower() or query in server['name'].lower() or query in server.get('description', '').lower():
            results[key] = server
    return results

def get_server_count():
    """Get total number of available servers."""
    return len(GAME_SERVERS)

def get_category_counts():
    """Get count of servers per category."""
    counts = {}
    for server in GAME_SERVERS.values():
        cat = server.get('category', 'other')
        counts[cat] = counts.get(cat, 0) + 1
    return counts
