#!/bin/bash
#
# Project Zomboid Dedicated Server Setup (Docker)
# Builds and runs a PZ server in a Docker container
#

set -e

# =============================================================================
# CONFIGURATION
# =============================================================================
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Source common library
source "${SCRIPT_DIR}/../lib/common.sh"

# Server configuration
readonly GAME_NAME="Project Zomboid"
readonly CONTAINER_NAME="pzserver"
readonly IMAGE_NAME="gameservers/projectzomboid"
readonly STEAM_APP_ID="380870"
readonly INSTALL_DIR="/home/steam/pzserver"

# Game server settings
readonly SERVER_NAME="Silverware PZ Server"
readonly ADMIN_PASSWORD="changeme"
readonly MAX_PLAYERS="16"
readonly MEMORY_MIN="2048m"
readonly MEMORY_MAX="4096m"

# Network ports
readonly SERVER_PORT="16261"
readonly UDP_PORT="16262"
readonly RCON_PORT="27015"

# Workshop mod configuration
WORKSHOP_ITEMS="${WORKSHOP_ITEMS:-}"
MODS="${MODS:-}"

# Data directory for persistent storage
DATA_DIR=""

# =============================================================================
# FUNCTIONS
# =============================================================================

check_prerequisites() {
    log_step 1 5 "Checking prerequisites..."

    if ! check_docker; then
        log_error "Docker is required. Please install Docker first."
        exit 1
    fi

    log_success "All prerequisites satisfied"
}

generate_dockerfile() {
    cat << 'EOF'
FROM debian:bookworm-slim

ENV DEBIAN_FRONTEND=noninteractive

RUN dpkg --add-architecture i386 && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
        ca-certificates \
        curl \
        lib32gcc-s1 \
        lib32stdc++6 \
        openjdk-17-jre-headless \
        locales \
    && rm -rf /var/lib/apt/lists/* \
    && locale-gen en_US.UTF-8

ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US:en

RUN useradd -m -s /bin/bash steam
WORKDIR /home/steam

RUN mkdir -p /home/steam/steamcmd && \
    cd /home/steam/steamcmd && \
    curl -sqL "https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz" | tar zxvf - && \
    chown -R steam:steam /home/steam

RUN mkdir -p /home/steam/pzserver && chown -R steam:steam /home/steam/pzserver
RUN mkdir -p /home/steam/Zomboid && chown -R steam:steam /home/steam/Zomboid

USER steam

RUN /home/steam/steamcmd/steamcmd.sh \
    +force_install_dir /home/steam/pzserver \
    +login anonymous \
    +app_update 380870 validate \
    +quit

WORKDIR /home/steam/pzserver

ENV LD_LIBRARY_PATH=/home/steam/pzserver/linux64:/home/steam/pzserver/natives:/home/steam/pzserver:/home/steam/pzserver/jre64/lib

EXPOSE 16261/udp 16262/udp 27015/tcp

ENTRYPOINT ["./start-server.sh"]
EOF
}

build_image() {
    log_step 2 5 "Building Docker image..."
    log_info "This may take a while for the initial download..."

    local dockerfile
    dockerfile="$(generate_dockerfile)"

    if ! build_docker_image "$IMAGE_NAME" "$dockerfile"; then
        log_error "Failed to build Docker image"
        exit 1
    fi
}

setup_data_directory() {
    log_step 3 5 "Setting up data directory..."

    DATA_DIR=$(create_game_data_dir "projectzomboid")
    mkdir -p "${DATA_DIR}/Server"
    mkdir -p "${DATA_DIR}/Saves"

    # Create server configuration file
    local config_file="${DATA_DIR}/Server/${CONTAINER_NAME}.ini"
    if [[ ! -f "$config_file" ]]; then
        log_info "Creating server configuration..."
        cat > "$config_file" << EOF
# Project Zomboid Server Configuration
# Generated by Silverware Game Servers Setup

PublicName=${SERVER_NAME}
PublicDescription=A Project Zomboid dedicated server
DefaultPort=${SERVER_PORT}
UDPPort=${UDP_PORT}
MaxPlayers=${MAX_PLAYERS}
Password=
RCONPort=${RCON_PORT}
RCONPassword=changeme_rcon

PauseEmpty=true
GlobalChat=true
Open=true
PVP=true
SafetySystem=true

Map=Muldraugh, KY
WorkshopItems=${WORKSHOP_ITEMS}
Mods=${MODS}

SteamVAC=true
EOF
        log_success "Server configuration created"
    fi

    log_success "Data directory ready: ${DATA_DIR}"
}

run_container() {
    log_step 4 5 "Starting Docker container..."

    local port_mappings="-p ${SERVER_PORT}:${SERVER_PORT}/udp -p ${UDP_PORT}:${UDP_PORT}/udp -p ${RCON_PORT}:${RCON_PORT}/tcp"
    local volume_mappings="-v ${DATA_DIR}:/home/steam/Zomboid"
    local extra_args="-servername ${CONTAINER_NAME} -adminpassword ${ADMIN_PASSWORD} -Xms${MEMORY_MIN} -Xmx${MEMORY_MAX}"

    if ! run_docker_container "$CONTAINER_NAME" "$IMAGE_NAME" "$port_mappings" "$volume_mappings" "$extra_args"; then
        log_error "Failed to start container"
        exit 1
    fi

    sleep 3
    if container_is_running "$CONTAINER_NAME"; then
        log_success "Container is running"
    else
        log_error "Container failed to start. Check logs with: docker logs ${CONTAINER_NAME}"
        exit 1
    fi
}

show_summary() {
    log_step 5 5 "Setup complete!"

    echo ""
    separator "=" 60
    echo -e "${BOLD}${GAME_NAME} Server Installation Summary${RESET}"
    separator "-" 60
    echo -e "  ${CYAN}Container Name:${RESET}     ${CONTAINER_NAME}"
    echo -e "  ${CYAN}Image Name:${RESET}         ${IMAGE_NAME}"
    echo -e "  ${CYAN}Data Directory:${RESET}     ${DATA_DIR}"
    echo -e "  ${CYAN}Max Players:${RESET}        ${MAX_PLAYERS}"
    echo -e "  ${CYAN}Memory:${RESET}             ${MEMORY_MIN} - ${MEMORY_MAX}"
    separator "-" 60
    echo -e "${BOLD}Network Ports:${RESET}"
    echo -e "  ${CYAN}Game Port:${RESET}          ${SERVER_PORT}/udp"
    echo -e "  ${CYAN}UDP Port:${RESET}           ${UDP_PORT}/udp"
    echo -e "  ${CYAN}RCON Port:${RESET}          ${RCON_PORT}/tcp"
    separator "-" 60
    echo -e "${BOLD}Default Credentials (CHANGE THESE!):${RESET}"
    echo -e "  ${YELLOW}Admin Password:${RESET}     ${ADMIN_PASSWORD}"
    separator "-" 60
    echo -e "${BOLD}Configuration Files:${RESET}"
    echo -e "  ${DIM}Server config:${RESET}   ${DATA_DIR}/Server/${CONTAINER_NAME}.ini"
    echo -e "  ${DIM}Sandbox opts:${RESET}    ${DATA_DIR}/Server/${CONTAINER_NAME}_SandboxVars.lua"
    separator "-" 60
    echo -e "${BOLD}Workshop Mods:${RESET}"
    if [[ -n "$WORKSHOP_ITEMS" ]]; then
        echo -e "  ${GREEN}Configured:${RESET}      ${WORKSHOP_ITEMS}"
    else
        echo -e "  ${DIM}None configured - edit WORKSHOP_ITEMS in setup script${RESET}"
    fi
    separator "-" 60
    echo -e "${BOLD}Useful Commands:${RESET}"
    echo -e "  ${GREEN}Start server:${RESET}    docker start ${CONTAINER_NAME}"
    echo -e "  ${GREEN}Stop server:${RESET}     docker stop ${CONTAINER_NAME}"
    echo -e "  ${GREEN}View logs:${RESET}       docker logs -f ${CONTAINER_NAME}"
    echo -e "  ${GREEN}Console access:${RESET}  docker attach ${CONTAINER_NAME}"
    separator "=" 60
    echo ""

    log_to_file "COMPLETE" "${GAME_NAME} Docker server setup finished successfully"
}

# =============================================================================
# MAIN
# =============================================================================

main() {
    log_header "${GAME_NAME} Server Setup (Docker)"
    log_to_file "START" "Beginning ${GAME_NAME} Docker server installation"

    check_prerequisites
    setup_data_directory
    build_image
    run_container
    show_summary

    return 0
}

main "$@"
