#!/bin/bash
#
# Project Zomboid Dedicated Server Setup
# Downloads, configures, and runs a PZ server using SteamCMD
#

set -e

# =============================================================================
# CONFIGURATION
# =============================================================================
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Source common library
source "${SCRIPT_DIR}/../lib/common.sh"

# Server configuration
readonly GAME_NAME="Project Zomboid"
readonly SERVICE_NAME="pzserver"
readonly STEAM_APP_ID="380870"
readonly INSTALL_DIR="/opt/pzserver"
readonly WORKING_DIR="${INSTALL_DIR}"
readonly SERVER_BINARY="${INSTALL_DIR}/start-server.sh"

# Game server settings
readonly SERVER_NAME="Silverware PZ Server"
readonly ADMIN_PASSWORD="changeme"
readonly SERVER_PASSWORD=""
readonly MAX_PLAYERS="16"
readonly SERVER_PORT="16261"
readonly UDP_PORT="16262"
readonly RCON_PORT="27015"
readonly RCON_PASSWORD="changeme_rcon"

# Memory settings (adjust based on your server)
readonly MEMORY_MIN="2048m"
readonly MEMORY_MAX="4096m"

# Server data directories
readonly SERVER_DATA_DIR="/home/pzuser/Zomboid"
readonly SERVER_CONFIG_DIR="${SERVER_DATA_DIR}/Server"

# Screen session name
readonly SCREEN_NAME="${SERVICE_NAME}"

# Dedicated user for the server (security best practice)
readonly SERVER_USER="pzuser"

# =============================================================================
# FUNCTIONS
# =============================================================================

# Validate prerequisites
check_prerequisites() {
    log_step 1 8 "Checking prerequisites..."

    local deps=("curl" "tar" "screen" "systemctl" "java")

    # Check for basic dependencies first (excluding java)
    local basic_deps=("curl" "tar" "screen" "systemctl")
    if ! check_dependencies "${basic_deps[@]}"; then
        log_error "Missing basic dependencies. Please install them first."
        exit 1
    fi

    # Check for Java (required for PZ server)
    if ! command_exists java; then
        log_warn "Java not found. Project Zomboid requires Java 17+."
        log_info "Install with: apt-get install openjdk-17-jre-headless"

        if confirm "Would you like to attempt installing Java now?"; then
            log_info "Installing Java..."
            apt-get update && apt-get install -y openjdk-17-jre-headless
        else
            log_error "Java is required. Please install it and re-run this script."
            exit 1
        fi
    fi

    # Verify Java version
    local java_version
    java_version=$(java -version 2>&1 | head -n1 | cut -d'"' -f2 | cut -d'.' -f1)
    if [[ "$java_version" -lt 17 ]]; then
        log_warn "Java version ${java_version} detected. PZ recommends Java 17+."
    else
        log_info "Java ${java_version} detected"
    fi

    log_success "All prerequisites satisfied"
}

# Create dedicated user for the server
setup_server_user() {
    log_step 2 8 "Setting up server user..."

    if id "$SERVER_USER" &>/dev/null; then
        log_info "User ${SERVER_USER} already exists"
    else
        log_info "Creating dedicated user: ${SERVER_USER}"
        useradd -m -s /bin/bash "$SERVER_USER"
        log_success "User ${SERVER_USER} created"
    fi
}

# Install SteamCMD
setup_steamcmd() {
    log_step 3 8 "Setting up SteamCMD..."

    if ! install_steamcmd; then
        log_error "Failed to install SteamCMD"
        exit 1
    fi
}

# Download/update game files
download_game_files() {
    log_step 4 8 "Downloading ${GAME_NAME} server files..."
    log_info "This may take a while for the initial download..."

    # Create install directory if needed
    if [[ ! -d "$INSTALL_DIR" ]]; then
        log_info "Creating install directory: ${INSTALL_DIR}"
        mkdir -p "$INSTALL_DIR"
    fi

    if ! run_steamcmd "$INSTALL_DIR" "$STEAM_APP_ID"; then
        log_error "Failed to download game files"
        exit 1
    fi

    # Set ownership to server user
    chown -R "${SERVER_USER}:${SERVER_USER}" "$INSTALL_DIR"

    log_success "Game files downloaded and permissions set"
}

# Create server configuration
configure_server() {
    log_step 5 8 "Configuring server..."

    # Create server data directory
    mkdir -p "$SERVER_CONFIG_DIR"

    # Create server configuration file
    local config_file="${SERVER_CONFIG_DIR}/${SERVICE_NAME}.ini"

    log_info "Creating server configuration: ${config_file}"

    cat > "$config_file" << EOF
# Project Zomboid Server Configuration
# Generated by Silverware Game Servers Setup

# Server Identity
PublicName=${SERVER_NAME}
PublicDescription=A Project Zomboid dedicated server

# Connection Settings
DefaultPort=${SERVER_PORT}
UDPPort=${UDP_PORT}
MaxPlayers=${MAX_PLAYERS}

# Passwords
Password=${SERVER_PASSWORD}
RCONPort=${RCON_PORT}
RCONPassword=${RCON_PASSWORD}

# Server Settings
PauseEmpty=true
GlobalChat=true
Open=true
AutoCreateUserInWhiteList=false
DisplayUserName=true
ShowFirstAndLastName=false

# PVP Settings
PVP=true
SafetySystem=true
ShowSafety=true
SafetyToggleTimer=2
SafetyCooldownTimer=3

# Shared Map Settings
ItemNumbersLimitPerContainer=0
TrashDeleteAll=false
PVPMeleeWhileHitReaction=false
PVPFirearmDamageModifier=50
PVPMeleeDamageModifier=30
PVPMeleeWhileHitReaction=false

# Anti-Cheat
AntiCheatProtectionType1=true
AntiCheatProtectionType2=true
AntiCheatProtectionType3=true
AntiCheatProtectionType4=true
AntiCheatProtectionType5=true
AntiCheatProtectionType6=true
AntiCheatProtectionType7=true
AntiCheatProtectionType8=true
AntiCheatProtectionType9=true
AntiCheatProtectionType10=true
AntiCheatProtectionType11=true
AntiCheatProtectionType12=true
AntiCheatProtectionType13=true
AntiCheatProtectionType14=true
AntiCheatProtectionType15=true
AntiCheatProtectionType16=true
AntiCheatProtectionType17=true
AntiCheatProtectionType18=true
AntiCheatProtectionType19=true
AntiCheatProtectionType20=true

# Map
Map=Muldraugh, KY

# Mods (comma-separated workshop IDs)
WorkshopItems=
Mods=

# Steam Settings
SteamVAC=true
EOF

    # Create server startup script with memory settings
    local startup_script="${INSTALL_DIR}/start-server-custom.sh"
    cat > "$startup_script" << EOF
#!/bin/bash
cd "${INSTALL_DIR}"
export JAVA_HOME=\$(dirname \$(dirname \$(readlink -f \$(which java))))
./start-server.sh -servername ${SERVICE_NAME} -adminpassword ${ADMIN_PASSWORD} -Xms${MEMORY_MIN} -Xmx${MEMORY_MAX}
EOF
    chmod +x "$startup_script"

    # Set ownership
    chown -R "${SERVER_USER}:${SERVER_USER}" "$SERVER_DATA_DIR"
    chown -R "${SERVER_USER}:${SERVER_USER}" "$INSTALL_DIR"

    log_success "Server configured"
}

# Generate systemd service file content
generate_service_file() {
    cat << EOF
[Unit]
Description=${GAME_NAME} Dedicated Server
After=network.target

[Service]
Type=forking
User=${SERVER_USER}
Group=${SERVER_USER}
WorkingDirectory=${WORKING_DIR}
Environment="LD_LIBRARY_PATH=${INSTALL_DIR}/linux64:${INSTALL_DIR}/natives:${INSTALL_DIR}:${INSTALL_DIR}/jre64/lib"
ExecStart=/usr/bin/screen -dmS "${SCREEN_NAME}" ${INSTALL_DIR}/start-server-custom.sh
ExecStop=/usr/bin/screen -S "${SCREEN_NAME}" -p 0 -X stuff "quit^M"
ExecStop=/bin/sleep 10
Restart=on-failure
RestartSec=30

[Install]
WantedBy=multi-user.target
EOF
}

# Create systemd service
setup_systemd_service() {
    log_step 6 8 "Creating systemd service..."

    local service_content
    service_content="$(generate_service_file)"

    if ! create_systemd_service "$SERVICE_NAME" "$service_content"; then
        log_error "Failed to create systemd service"
        exit 1
    fi
}

# Enable and start the service
start_service() {
    log_step 7 8 "Enabling and starting service..."

    if ! enable_service "$SERVICE_NAME"; then
        log_error "Failed to start service"
        exit 1
    fi
}

# Display completion summary
show_summary() {
    log_step 8 8 "Setup complete!"

    echo ""
    separator "=" 60
    echo ""
    echo -e "${BOLD}${GAME_NAME} Server Installation Summary${RESET}"
    echo ""
    separator "-" 60
    echo -e "  ${CYAN}Install Directory:${RESET}  ${INSTALL_DIR}"
    echo -e "  ${CYAN}Config Directory:${RESET}   ${SERVER_CONFIG_DIR}"
    echo -e "  ${CYAN}Service Name:${RESET}       ${SERVICE_NAME}"
    echo -e "  ${CYAN}Server Name:${RESET}        ${SERVER_NAME}"
    echo -e "  ${CYAN}Server User:${RESET}        ${SERVER_USER}"
    echo -e "  ${CYAN}Max Players:${RESET}        ${MAX_PLAYERS}"
    echo -e "  ${CYAN}Memory:${RESET}             ${MEMORY_MIN} - ${MEMORY_MAX}"
    separator "-" 60
    echo ""
    echo -e "${BOLD}Network Ports:${RESET}"
    echo -e "  ${CYAN}Game Port:${RESET}          ${SERVER_PORT}/udp"
    echo -e "  ${CYAN}UDP Port:${RESET}           ${UDP_PORT}/udp"
    echo -e "  ${CYAN}RCON Port:${RESET}          ${RCON_PORT}/tcp"
    separator "-" 60
    echo ""
    echo -e "${BOLD}Default Credentials (CHANGE THESE!):${RESET}"
    echo -e "  ${YELLOW}Admin Password:${RESET}     ${ADMIN_PASSWORD}"
    echo -e "  ${YELLOW}RCON Password:${RESET}      ${RCON_PASSWORD}"
    separator "-" 60
    echo ""
    echo -e "${BOLD}Useful Commands:${RESET}"
    echo -e "  ${GREEN}Start server:${RESET}    systemctl start ${SERVICE_NAME}"
    echo -e "  ${GREEN}Stop server:${RESET}     systemctl stop ${SERVICE_NAME}"
    echo -e "  ${GREEN}Restart server:${RESET}  systemctl restart ${SERVICE_NAME}"
    echo -e "  ${GREEN}Server status:${RESET}   systemctl status ${SERVICE_NAME}"
    echo -e "  ${GREEN}View console:${RESET}    sudo -u ${SERVER_USER} screen -r ${SCREEN_NAME}"
    echo ""
    echo -e "${BOLD}Configuration Files:${RESET}"
    echo -e "  ${DIM}Server config:${RESET}   ${SERVER_CONFIG_DIR}/${SERVICE_NAME}.ini"
    echo -e "  ${DIM}Sandbox opts:${RESET}    ${SERVER_CONFIG_DIR}/${SERVICE_NAME}_SandboxVars.lua"
    echo ""
    separator "-" 60
    echo ""
    echo -e "${YELLOW}IMPORTANT:${RESET} Change the default passwords in:"
    echo -e "  ${SERVER_CONFIG_DIR}/${SERVICE_NAME}.ini"
    echo ""
    echo -e "${YELLOW}Firewall:${RESET} Open these ports if using a firewall:"
    echo -e "  ufw allow ${SERVER_PORT}/udp"
    echo -e "  ufw allow ${UDP_PORT}/udp"
    echo -e "  ufw allow ${RCON_PORT}/tcp"
    echo ""
    separator "=" 60
    echo ""

    log_to_file "COMPLETE" "${GAME_NAME} server setup finished successfully"
}

# =============================================================================
# MAIN
# =============================================================================

main() {
    log_header "${GAME_NAME} Server Setup"
    log_to_file "START" "Beginning ${GAME_NAME} server installation"

    check_prerequisites
    setup_server_user
    setup_steamcmd
    download_game_files
    configure_server
    setup_systemd_service
    start_service
    show_summary

    return 0
}

# Run main function
main "$@"
